include: package:flutter_lints/flutter.yaml

linter:
  rules:
  require_trailing_commas: true
  prefer_const_constructors: true
  prefer_const_declarations: true
  prefer_final_fields: true
  depend_on_referenced_packages: false